### PR TITLE
Add the codestream API

### PR DESCRIPTION
**Pull request by hmalphettes**
Hi there and thanks for publishing the SDK!

Here is my attempt to add the codestream API to it.
Please note that I needed to patch the go-swagger templates for the generated code for codestream to compile: https://github.com/go-swagger/go-swagger/pull/2190

I hope this helps and I'll keep this updated as I get t use it.

### CODE REVIEW

**Comment by markpeek** [comment]
Thank you @hmalphettes for this change. Given the need for an upstream go-swagger change, I'm going to hold on this until that dependency is resolved. That way we can lock in the version of go-swagger needed for recreating this code.

**Comment by hmalphettes** [comment]
@markpeek , the go-swagger change was merged: https://github.com/go-swagger/go-swagger/pull/2190#pullrequestreview-348323016

No hurry at all on my side:
- We can wait for the next release of the go-swagger changes
- I will pull this personal fork at work and confirm that the API behaves as expected.

**Comment by sammcgeown** [comment]
Hi @markpeek - is this planned to be merged at some point? I could use the Code Stream API objects :)

**Comment by vrabbi** [comment]
Any plan to merge this? The go swagger was released with the fix a while ago. This would be great to have in the sdk

**Pull request closed without merging**
